name: abiba
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  english_words: ^4.0.0
  provider: ^6.0.0
  requests: ^4.7.0
  intl: ^0.19.0
  audioplayers: ^6.0.0
  path_provider: ^2.1.2
  file_picker: ^6.1.1
  flutter_typeahead: ^4.0.0
  sliding_up_panel: ^2.0.0

  cupertino_icons: ^1.0.6
  fl_chart: ^0.66.0
  syncfusion_flutter_charts: ^24.2.9
  excel: ^4.0.2
  shared_preferences: ^2.2.3

  http: any
  pdf: ^3.10.8
  printing: ^5.12.0


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0


flutter:
  assets:
    - assets/fonts/NotoSans-Regular.ttf
    - assets/fonts/NotoSans-Bold.ttf


  uses-material-design: true
