version: '3'

services:
  postgres:
    image: postgres
    ports:
      - "5432:5432"
    volumes:
      - ../docker-postgresql-multiple-databases:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: radio
    restart: always
