version: '3.8'

services:
  postgres:
    image: postgres
    ports:
      - "5432:5432"
    volumes:
      - ./docker-postgresql-multiple-databases:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_USER: megaUserToNotBeHacked
      POSTGRES_PASSWORD: thisPasswordIsNeverGoingToBeHacked
      POSTGRES_DB: radio
    restart: always

  audiocaptureserver:
    image: audiocaptureserver:latest
    build:
      context: ./AudioCaptureServer
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      - postgres
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Host=postgres;Database=radio;Username=user;Password=password

  recognizer:
    build: ./Recognizer
    volumes:
      - ./Recognizer:/app
    depends_on:
      - postgres
      - audiocaptureserver
    entrypoint: ["python3", "main.py"]

networks:
  default:
    driver: bridge

